"""Add A+ content tables

Revision ID: 38b233e71c9a
Revises: [自动生成的ID]
Create Date: 2025-09-26 09:03:42.011094

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "38b233e71c9a"
down_revision = "[自动生成的ID]"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amazon_aplus_contents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("brand_story", sa.Text(), nullable=True),
        sa.Column("faq", sa.JSON(), nullable=True),
        sa.Column("product_information", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["amazon_products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id"),
    )
    op.create_table(
        "amazon_aplus_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("original_url", sa.Text(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("alt_text", sa.Text(), nullable=True),
        sa.Column("image_type", sa.String(), nullable=True),
        sa.Column("content_section", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint(
            "image_type IN ('detail', 'scene', 'lifestyle', 'comparison', 'infographic')",
            name="ck_aplus_image_type",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'stored', 'failed')", name="ck_aplus_image_status"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["amazon_products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("amazon_aplus_images")
    op.drop_table("amazon_aplus_contents")
    # ### end Alembic commands ###
